# Generated by Django 5.1.7 on 2025-03-30 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='value',
            new_name='first_name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='type',
        ),
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='last_name',
            field=models.CharField(default='default_lastname', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='middle_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(default='default_lastname', max_length=20),
            preserve_default=False,
        ),
    ]
